# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NEXT_WEBSITE_URL: ${{secrets.NEXT_WEBSITE_URL}}

    steps:
    - uses: actions/checkout@v4
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'
    - name: Show Node.js version    
      run: node --version

    - name: Show Node.js path
      run: which node

    - name: Show npm path
      run: which npm

    - name: npm config get registry
      run: npm config get registry

    - name: Install dependencies using npm ci
      run: npm ci

    - run: npm run build --if-present

    - name: 修改目录
      run: cd /home/susu/actions-runner/_work/nextjs-cloud-demo/nextjs-cloud-demo

    - name: pm2 list 
      run: pm2 list
